apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: escoutly
resources:
  - namespace.yaml
  - secrets.example.yaml # replace with secrets.yaml in real envs
  - postgres.yaml
  - services.yaml
  - ingress.yaml
